"""
analyze_filters.py — Test different filter combinations across all seasons.

Reads the backtest CSVs already generated by backtest_real_odds.py --all
and shows ROI/volume at different filter settings.

Run: python analyze_filters.py
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))

import pandas as pd
import numpy as np
from src.edge import american_to_decimal, implied_prob_from_american, calculate_edge

LOG_DIR = Path("logs")

# Load all available backtest CSVs
season_map = {
    2020: "2019-20", 2021: "2020-21", 2022: "2021-22",
    2023: "2022-23", 2024: "2023-24", 2025: "2024-25",
    2026: "2025-26",
}

all_dfs = []
for yr, season in season_map.items():
    path = LOG_DIR / f"backtest_real_{yr}.csv"
    if path.exists():
        df = pd.read_csv(path)
        df["season"] = season
        all_dfs.append(df)

if not all_dfs:
    print("No backtest CSVs found. Run: python backtest_real_odds.py --all --edge 12")
    sys.exit(1)

raw = pd.concat(all_dfs, ignore_index=True)
raw["model_prob_home"] = pd.to_numeric(raw["model_prob_home"], errors="coerce")
raw["moneyline_home"]  = pd.to_numeric(raw["moneyline_home"],  errors="coerce")
raw["moneyline_away"]  = pd.to_numeric(raw["moneyline_away"],  errors="coerce")
raw["home_won"]        = pd.to_numeric(raw["home_won"],        errors="coerce")

print(f"Loaded {len(raw)} games across {len(all_dfs)} seasons")
print()

# Recompute bets fresh for each filter config
def run_filter(df, min_edge, max_edge, min_odds, max_odds, underdogs_only):
    results = []
    for _, row in df.iterrows():
        p_home = row["model_prob_home"]
        h_odds = row["moneyline_home"]
        a_odds = row["moneyline_away"]

        if pd.isna(p_home) or pd.isna(h_odds) or pd.isna(a_odds):
            continue

        p_away = 1 - p_home
        fair_h, fair_a = implied_prob_from_american(h_odds, a_odds)
        edge_h = calculate_edge(p_home, fair_h)
        edge_a = calculate_edge(p_away, fair_a)

        # Pick best side
        if edge_h >= min_edge and edge_h >= edge_a:
            bet_odds, bet_edge, is_home = h_odds, edge_h, True
        elif edge_a >= min_edge:
            bet_odds, bet_edge, is_home = a_odds, edge_a, False
        else:
            continue

        # Apply filters
        if underdogs_only and bet_odds < 0:       continue
        if bet_odds > max_odds:                    continue
        if bet_odds <= abs(min_odds):              continue
        if bet_edge > max_edge:                    continue

        home_won = row["home_won"]
        if pd.isna(home_won): continue
        won = (is_home == (int(home_won) == 1))
        dec = american_to_decimal(bet_odds)
        pnl = (dec - 1) if won else -1.0

        results.append({
            "season":   row["season"],
            "is_home":  is_home,
            "bet_odds": bet_odds,
            "bet_edge": bet_edge,
            "won":      won,
            "pnl":      pnl,
        })

    return pd.DataFrame(results)


# Define filter configs to test
configs = [
    # label,                    min_e, max_e, min_odds, max_odds, underdogs_only
    ("Current  (12%, u/d, +141–+500, <30%)",  12,  30,  -140,  500, True),
    ("Edge 8%  (everything else same)",         8,  30,  -140,  500, True),
    ("Edge 10% (everything else same)",        10,  30,  -140,  500, True),
    ("No max_edge cap  (allow >30%)",          12, 999,  -140,  500, True),
    ("No max_odds cap  (allow >+500)",         12,  30,  -140, 9999, True),
    ("No min_odds filter (allow near-even)",   12,  30, -9999,  500, True),
    ("All underdogs, edge 8%, no caps",         8, 999,  -140, 9999, True),
    ("Include favorites, edge 12%",            12,  30, -9999,  500, False),
    ("Include favorites, edge 8%",              8, 999, -9999, 9999, False),
]

print(f"{'Config':48s} {'Bets':6s} {'Bets/yr':8s} {'WR':7s} {'ROI':8s}")
print("-" * 82)

n_seasons = len(all_dfs)
recent_seasons = ["2023-24", "2024-25", "2025-26"]

for label, min_e, max_e, min_o, max_o, dogs_only in configs:
    df = run_filter(raw, min_e, max_e, min_o, max_o, dogs_only)
    if df.empty:
        print(f"  {label:46s}  no bets")
        continue

    total = len(df)
    wr    = df["won"].mean()
    roi   = df["pnl"].sum() / total * 100
    bpy   = total / n_seasons

    # Recent seasons only
    rec = df[df["season"].isin(recent_seasons)]
    rec_roi = rec["pnl"].sum() / len(rec) * 100 if len(rec) else 0
    rec_tag = f"  [recent: {rec_roi:+.0f}%]"

    print(f"  {label:46s} {total:5d}  {bpy:5.0f}/yr  {wr:.1%}  {roi:+6.1f}%{rec_tag}")

print("-" * 82)
print()
print("Notes:")
print("  'recent' = 2023-24 + 2024-25 only (most predictive of future performance)")
print("  Bets/yr = avg bets per season")
print("  WR = overall win rate across all seasons")